services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab.local

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.test.local'

        # GitLab derrière proxy
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['gitlab_https'] = true

        # Autoriser le reverse proxy Traefik
        gitlab_rails['trusted_proxies'] = ['172.18.0.0/16', '127.0.0.1']

        # SSH
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.test.local`)"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
     
    networks:
      - traefik_network

    ports:
      # - "8080:80"
      # - "9443:443"
      - "2222:22"

    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab

    shm_size: "256m"

networks:
  traefik_network:
    external: true